on:
  pull_request:
    paths-ignore:
      - "**/*.md"
  push:
    branches:
      - master
      - main
      - develop
      - support/*
    paths-ignore:
      - "**/*.md"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: arduino/arduino-lint-action@v1
        with:
          library-manager: update

  build-examples:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        fqbn:
          - "esp32:esp32:esp32"
          - "esp32:esp32:esp32s3"
          - "esp32:esp32:esp32c3"
        nimble:
          - false
          - '1.4.0'
          - '2.3.2'
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.fqbn }}
          sketch-paths: |
            - examples/SerialToSerialBLE
          libraries: |
            - source-path: ./
            ${{ matrix.nimble != false && format('- name: NimBLE-Arduino@{0}', matrix.nimble) || '' }}
          cli-compile-flags: |
            - --build-property 
            - build.extra_flags="-DBLESERIAL_USE_NIMBLE=${{ matrix.nimble != false }}"