on:
  pull_request:
    paths-ignore:
      - "**/*.md"
  push:
    branches:
      - master
      - main
      - develop
      - support/*
    paths-ignore:
      - "**/*.md"

jobs:
  platformio:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        example:
          - "SerialToSerialBLE"
          # - "SerialToSerialBLE_TransparentUART"
          - "SerialToSerialBLE_TransparentUART-NimBLE"
          # - "SerialToSerialBLE_Secure"
        boards:
          - [ esp32dev, esp32-s3-devkitc-1, esp32-c3-devkitm-1 ]
        nimble:
          - false
          - '^1.4.0'
          - '^2.0.0'

        exclude:
          - example: "SerialToSerialBLE_TransparentUART-NimBLE"
            nimble: false
        #   - example: "SerialToSerialBLE_TransparentUART"
        #     nimble: '^1.4.0'
        #   - example: "SerialToSerialBLE_TransparentUART"
        #     nimble: '^2.0.0'
        include:
          - example: "SerialToSerialBLE_TransparentUART-NimBLE"
            nimble: '^2.0.0'
            os: ubuntu-latest
            boards: [esp32dev, esp32-s3-devkitc-1, esp32-c3-devkitm-1]
          - example: "SerialToSerialBLE_TransparentUART-NimBLE"
            nimble: '^1.4.0'
            os: ubuntu-latest
            boards: [esp32dev, esp32-s3-devkitc-1, esp32-c3-devkitm-1]

          - example: "SerialToSerialBLE_Secure"
            nimble: false
            os: ubuntu-latest
            boards: [esp32dev, esp32-s3-devkitc-1, esp32-c3-devkitm-1]

    steps:
      - uses: actions/checkout@v4

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: |
            ~/.platformio/.cache
            ./.pio
          key: ${{ runner.os }}-pio-${{ hashFiles('**/*.ini') }}
          restore-keys: |
            ${{ runner.os }}-pio-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
          pio upgrade --dev
          pio pkg update --global

      - name: Build example
        run: |
          pio ci --lib="." --board=${{ join(matrix.boards, ' --board=') }} ${{ matrix.nimble && format('--project-option="lib_deps=h2zero/NimBLE-Arduino@{0}"', matrix.nimble) || '' }}
        env:
          PLATFORMIO_CI_SRC: "./examples/${{ matrix.example }}/*.ino"
          PLATFORMIO_BUILD_UNFLAGS: |
            -std=gnu++11
          PLATFORMIO_BUILD_FLAGS: |
            -std=gnu++17
            -D BLESERIAL_USE_NIMBLE=${{ matrix.nimble != false }}
            -Wall
            -Wextra
            -Wpedantic
